-- Empty jarihana_dev database only; schema baseline: ddc0fab.
-- Included: 2026-09-01-member-type-and-name-policy.sql and 2026-09-26-feedback.sql.
-- Existing databases require reviewed incremental migrations, not this bootstrap.
BEGIN;

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crew_name VARCHAR(4) NOT NULL,
    generation INTEGER,
    member_type VARCHAR(20) NOT NULL CHECK (member_type IN ('CREW', 'COACH')),
    github_id VARCHAR(50) NOT NULL,
    course VARCHAR(20) CHECK (course IN ('BACKEND', 'FRONTEND', 'ANDROID')),
    withdrawn_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_member_github_id UNIQUE (github_id),
    CONSTRAINT uk_member_crew_name_generation UNIQUE (crew_name, generation),
    CONSTRAINT ck_member_profile_fields CHECK (
        (member_type = 'COACH' AND course IS NULL AND generation IS NULL)
        OR (member_type = 'CREW' AND course IS NOT NULL AND generation > 0)
    )
);

CREATE UNIQUE INDEX uk_member_coach_name ON member (crew_name) WHERE member_type = 'COACH';

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL CHECK (type IN ('CLUB', 'STUDY', 'SESSION')),
    meeting_type VARCHAR(20) NOT NULL CHECK (meeting_type IN ('ONLINE', 'OFFLINE', 'FLEXIBLE')),
    location VARCHAR(255),
    recurring_activity_days VARCHAR(255),
    recurring_start_time TIME(6),
    recurring_end_time TIME(6),
    session_date DATE,
    session_start_time TIME(6),
    session_end_time TIME(6),
    name VARCHAR(50) NOT NULL,
    introduction VARCHAR(100) NOT NULL,
    description VARCHAR(10000),
    representative_image_key VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'ENDED')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_groups_name UNIQUE (name)
);

CREATE TABLE group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups (id),
    member_id BIGINT NOT NULL REFERENCES member (id),
    role VARCHAR(20) NOT NULL CHECK (role IN ('LEADER', 'MEMBER')),
    joined_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_group_member_group_member UNIQUE (group_id, member_id)
);

CREATE TABLE group_recruitment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups (id),
    join_method VARCHAR(20) NOT NULL CHECK (join_method IN ('AUTO', 'APPROVAL')),
    capacity INTEGER NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    ends_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruitment_id BIGINT NOT NULL REFERENCES group_recruitment (id),
    member_id BIGINT NOT NULL REFERENCES member (id),
    message VARCHAR(1000),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reject_reason VARCHAR(1000),
    registered_at TIMESTAMP(6) NOT NULL,
    decided_at TIMESTAMP(6),
    decided_by_type VARCHAR(255) CHECK (decided_by_type IN ('SYSTEM', 'MEMBER')),
    decided_by_member_id BIGINT,
    leader_viewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member (id),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash)
);

CREATE TABLE image_upload (
    id UUID PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    image_key VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_feedback_member_id FOREIGN KEY (member_id) REFERENCES member (id)
);

-- Spring Session JDBC 4.1.0: org/springframework/session/jdbc/schema-postgresql.sql.
CREATE TABLE spring_session (
    primary_id CHAR(36) NOT NULL,
    session_id CHAR(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INTEGER NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(100),
    CONSTRAINT spring_session_pk PRIMARY KEY (primary_id)
);

CREATE UNIQUE INDEX spring_session_ix1 ON spring_session (session_id);
CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE spring_session_attributes (
    session_primary_id CHAR(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id)
        REFERENCES spring_session (primary_id) ON DELETE CASCADE
);

COMMIT;
