BEGIN;
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS ck_notifications_event_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notifications_event_type CHECK (
    event_type IN ('GROUP_CREATED', 'REGISTRATION_SUBMITTED', 'PARTICIPANT_JOINED',
                   'REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'REGISTRATION_SYSTEM_REJECTED')
);
COMMIT;
