spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    jdbc:
      initialize-schema: always

jarihana:
  auth:
    cookie:
      secure: false
    local-development:
      enabled: true
      member-id: 1
