SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE refresh_token RESTART IDENTITY;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE SPRING_SESSION_ATTRIBUTES;
TRUNCATE TABLE SPRING_SESSION;
SET REFERENTIAL_INTEGRITY TRUE;
