SET
REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE refresh_token RESTART IDENTITY;
TRUNCATE TABLE registration RESTART IDENTITY;
TRUNCATE TABLE group_member RESTART IDENTITY;
TRUNCATE TABLE group_recruitment RESTART IDENTITY;
TRUNCATE TABLE groups RESTART IDENTITY;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE SPRING_SESSION_ATTRIBUTES;
TRUNCATE TABLE SPRING_SESSION;
SET
REFERENTIAL_INTEGRITY TRUE;
